development:
  adapter: postgresql
  encoding: unicode
  database: venuepilot
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: venuepilot_test
  pool: 5

production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>